sqlplus command line codes

SQL> create table Personel
(
  2  PERSONEL_ID NUMBER,
  3  FIRST_NAME CHAR(30),
  4  LAST_NAME VARCHAR2(30),
  5  JOB_TITLE VARCHAR2(15),
  6  YEAR_OF_EXPERIENCE INTERVAL YEAR TO MONTH,
  7  FLIGHT_TIME INTERVAL DAY TO SECOND,
  8  APPROVAL_DATE TIMESTAMP,
  9  HIRE_DATE DATE,
 10  PRIMARY KEY(PERSONEL_ID)
 11  );

Table created.

INSERT INTO PERSONEL
(
    PERSONEL_ID,
    FIRST_NAME,
    LAST_NAME,
    JOB_TITLE,
    YEAR_OF_EXPERIENCE,
    FLIGHT_TIME,
    APPROVAL_DATE,
    HIRE_DATE
)
VALUES
(
    2,
    'Veli',
    'Yıldız',
    'PL/SQL Dev',
    INTERVAL '1' MONTH,
    INTERVAL '14 12:09:22.111' DAY TO SECOND,
    CURRENT_TIMESTAMP,
    TRUNC(CURRENT_TIMESTAMP)
);

select * from personel